// ---------------------------------------------------------------------------
#ifdef __cplusplus
extern "C" {
#endif
// ---------------------------------------------------------------------------
//------------------------------------------------------------
//  Project: Open Tools for Xbase++                          -
//  Repository : http://www.xbwin.com                        -
//  Author: Pablo Botella Navarro ( http://www.xbwin.com )   -
//------------------------------------------------------------

// ---------------------------------------------------------------------------
// ot4xb.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB(XppParamList );
XPPRET XPPENTRY APPINSTANCE(XppParamList );
XPPRET XPPENTRY GETCURRENTPROCESSHANDLE(XppParamList );
XPPRET XPPENTRY GETHKERNEL32(XppParamList );
XPPRET XPPENTRY GETHUSER32(XppParamList );
XPPRET XPPENTRY GETHSHELL32(XppParamList );
XPPRET XPPENTRY GETHOT4XB(XppParamList );
XPPRET XPPENTRY OT4XB_CREATEGENERICWINDOW(XppParamList );
XPPRET XPPENTRY OT4XB_SUBCLASSWINDOW(XppParamList );
XPPRET XPPENTRY DELEGATED_XBASE_CALL(XppParamList );
XPPRET XPPENTRY DELEGATED_FPQCALL(XppParamList );
XPPRET XPPENTRY DELEGATED_EVAL(XppParamList );
XPPRET XPPENTRY OT4XB_REGISTER_DELEGATE_HWND(XppParamList );
XPPRET XPPENTRY OT4XB_SINGLE_INSTANCE(XppParamList );
XPPRET XPPENTRY OT4XB_HOOKTHREAD(XppParamList );
XPPRET XPPENTRY OT4XB_UNHOOKTHREAD(XppParamList );
// ---------------------------------------------------------------------------
XPPRET XPPENTRY _OT4XB_TASK_INTERNAL_PROC_(XppParamList );
XPPRET XPPENTRY OT4XB_TASK_ID(XppParamList );
XPPRET XPPENTRY OT4XB_TASK_RUN(XppParamList );
XPPRET XPPENTRY OT4XB_TASK_WAIT(XppParamList );
XPPRET XPPENTRY OT4XB_TASK_POP(XppParamList );
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB_UNMANGLE_CPP_NAME(XppParamList );
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB_APC_SEND_CB(XppParamList );
XPPRET XPPENTRY OT4XB_APC_POST_CB(XppParamList );
XPPRET XPPENTRY OT4XB_APC_POST_CB_H(XppParamList );
XPPRET XPPENTRY OT4XB_PUSH_EXIT_CB(XppParamList );
XPPRET XPPENTRY OT4XB_AUTOMATIC_SCROLL_FOCUS(XppParamList );
XPPRET XPPENTRY OT4XB_PAINTTHEMSGBAR(XppParamList );
// ---------------------------------------------------------------------------






// ---------------------------------------------------------------------------
// TCriticalSection.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY TCRITICALSECTION(XppParamList );

// ---------------------------------------------------------------------------
// ot4xb_odbd.cpp
// ---------------------------------------------------------------------------





// ---------------------------------------------------------------------------
// TLdList.cpp
// ---------------------------------------------------------------------------

XPPRET XPPENTRY TLDLIST(XppParamList );

// ---------------------------------------------------------------------------
// OSVer.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY LISWIN9X(XppParamList );
XPPRET XPPENTRY LISXP(XppParamList );
XPPRET XPPENTRY LISVISTA(XppParamList );


// ---------------------------------------------------------------------------
// NumAndBytes.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY DWFIX(XppParamList );
XPPRET XPPENTRY DWMINUS(XppParamList );
XPPRET XPPENTRY EXTENDSIGN8(XppParamList );
XPPRET XPPENTRY EXTENDSIGN16(XppParamList );
XPPRET XPPENTRY UNSIGNED8(XppParamList );
XPPRET XPPENTRY UNSIGNED16(XppParamList );
XPPRET XPPENTRY UNSIGNED32(XppParamList );
XPPRET XPPENTRY LONG2DOUBLE(XppParamList );
XPPRET XPPENTRY DOUBLE2LONG(XppParamList );
XPPRET XPPENTRY wapimc_LOWORD(XppParamList );
XPPRET XPPENTRY wapimc_HIWORD(XppParamList );
XPPRET XPPENTRY wapimc_LOBYTE(XppParamList );
XPPRET XPPENTRY wapimc_HIBYTE(XppParamList );
XPPRET XPPENTRY wapimc_LONIBBLE(XppParamList );
XPPRET XPPENTRY wapimc_HINIBBLE(XppParamList );
XPPRET XPPENTRY wapimc_MAKEBYTE(XppParamList );
XPPRET XPPENTRY wapimc_MAKEWORD(XppParamList );
XPPRET XPPENTRY wapimc_MAKELONG(XppParamList );
XPPRET XPPENTRY wapimc_MAKELANGID(XppParamList );
XPPRET XPPENTRY wapimc_MAKELPARAM(XppParamList );
XPPRET XPPENTRY wapimc_MAKELRESULT(XppParamList );
XPPRET XPPENTRY wapimc_GET_X_LPARAM(XppParamList );
XPPRET XPPENTRY wapimc_GET_Y_LPARAM(XppParamList );
XPPRET XPPENTRY DWBYTEREV(XppParamList );
XPPRET XPPENTRY WHLBYTEREV(XppParamList );
XPPRET XPPENTRY PACKFLOAT32(XppParamList );
XPPRET XPPENTRY UNPACKFLOAT32(XppParamList );
XPPRET XPPENTRY OT4XB_PARSE_NUMBER(XppParamList );
XPPRET XPPENTRY OT4XB_PARSE_INT(XppParamList );

// ---------------------------------------------------------------------------
// DrTool.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY GETPROCCESSARGV(XppParamList );
XPPRET XPPENTRY GETCOMMANDLINE(XppParamList );
XPPRET XPPENTRY CAPPPATH(XppParamList );
XPPRET XPPENTRY CAPPDIR(XppParamList );
XPPRET XPPENTRY LMAKEPATH(XppParamList );
XPPRET XPPENTRY LCOPYFILE(XppParamList );
XPPRET XPPENTRY LDISKREADY(XppParamList );
XPPRET XPPENTRY CCREATETMPFILE(XppParamList );
XPPRET XPPENTRY CGETTMPPATH(XppParamList );
XPPRET XPPENTRY NGETDRIVETYPE(XppParamList );
XPPRET XPPENTRY LCHDIR(XppParamList );
XPPRET XPPENTRY CDRIVES(XppParamList );
XPPRET XPPENTRY ADRIVES(XppParamList );
XPPRET XPPENTRY _TDRIVEINFO_(XppParamList );
XPPRET XPPENTRY GETDRIVEINFO(XppParamList );
XPPRET XPPENTRY CGETSHORTFILENAME(XppParamList );
XPPRET XPPENTRY LISDIR(XppParamList );
XPPRET XPPENTRY LISFILE(XppParamList );
XPPRET XPPENTRY GETWINDIR(XppParamList );
XPPRET XPPENTRY GETSYSDIR(XppParamList );
XPPRET XPPENTRY CPATHCOMBINE(XppParamList );
XPPRET XPPENTRY CURLCOMBINE(XppParamList );
XPPRET XPPENTRY CPATHDEFEXT(XppParamList );
XPPRET XPPENTRY CPATHBUILDROOT(XppParamList );
XPPRET XPPENTRY ASPLITPATH(XppParamList );
XPPRET XPPENTRY CPATHCANONICALIZE(XppParamList );
XPPRET XPPENTRY CPATHGETEXT(XppParamList );
XPPRET XPPENTRY CPATHREMOVEEXT(XppParamList );
XPPRET XPPENTRY CPATHCHANGEEXT(XppParamList );
XPPRET XPPENTRY CPATHGETFILENAME(XppParamList );
XPPRET XPPENTRY CPATHREMOVEBACKSLASH(XppParamList );
XPPRET XPPENTRY CPATHADDBACKSLASH(XppParamList );
XPPRET XPPENTRY CPATHGETPATH(XppParamList );
XPPRET XPPENTRY CPATHGETROOT(XppParamList );
XPPRET XPPENTRY CPATHREMOVEROOT(XppParamList );
XPPRET XPPENTRY LPATHISRELATIVE(XppParamList );
XPPRET XPPENTRY wapist_WIN32_FIND_DATA(XppParamList );
XPPRET XPPENTRY CCPUSERIAL(XppParamList );
XPPRET XPPENTRY OT4XB_PUSHDIR(XppParamList );
XPPRET XPPENTRY OT4XB_POPDIR(XppParamList );
XPPRET XPPENTRY OT4XB_CURDIR(XppParamList );

// ---------------------------------------------------------------------------
// Bitwise.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY NOR(XppParamList );
XPPRET XPPENTRY NXOR(XppParamList );
XPPRET XPPENTRY NAND(XppParamList );
XPPRET XPPENTRY NANDNOT(XppParamList );
XPPRET XPPENTRY NNOT(XppParamList );
XPPRET XPPENTRY LAND(XppParamList );
XPPRET XPPENTRY NLSHIFT(XppParamList );
XPPRET XPPENTRY NRSHIFT(XppParamList );
XPPRET XPPENTRY NLROT(XppParamList );
XPPRET XPPENTRY NRROT(XppParamList );
XPPRET XPPENTRY NLROTBYTE(XppParamList );
XPPRET XPPENTRY NRROTBYTE(XppParamList );
XPPRET XPPENTRY NLROTWORD(XppParamList );
XPPRET XPPENTRY NRROTWORD(XppParamList );
XPPRET XPPENTRY LDWBITONOFF(XppParamList );


// --------------------------------------------------------------------------
// ot4xb_register.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB_SET_REGISTRY_VALUE_AS_STRING(XppParamList );
XPPRET XPPENTRY OT4XB_GET_REGISTRY_VALUE_AS_STRING(XppParamList );

// ---------------------------------------------------------------------------
// String.cpp
// ---------------------------------------------------------------------------

XPPRET XPPENTRY ASPLITTXTLINES(XppParamList );
XPPRET XPPENTRY TOKENIZE(XppParamList );
XPPRET XPPENTRY TOKENIZEEX(XppParamList );
XPPRET XPPENTRY __AJOIN(XppParamList );
XPPRET XPPENTRY NOCOMMENT(XppParamList );
XPPRET XPPENTRY NCRC32(XppParamList );
XPPRET XPPENTRY NCRC8(XppParamList );
XPPRET XPPENTRY CHRR(XppParamList );
XPPRET XPPENTRY MKSCSTR(XppParamList );
XPPRET XPPENTRY LSTRBITSET(XppParamList );
XPPRET XPPENTRY LPSTRBITSET(XppParamList );
XPPRET XPPENTRY CSTRBITNOT(XppParamList );
XPPRET XPPENTRY PSTRBITNOT(XppParamList );
XPPRET XPPENTRY CSTRBITOR(XppParamList );
XPPRET XPPENTRY CSTRBITXOR(XppParamList );
XPPRET XPPENTRY CSTRBITAND(XppParamList );
XPPRET XPPENTRY PSTRBITOR(XppParamList );
XPPRET XPPENTRY PSTRBITXOR(XppParamList );
XPPRET XPPENTRY PSTRBITAND(XppParamList );
XPPRET XPPENTRY ASTRBITS(XppParamList );
XPPRET XPPENTRY NSTRBITCOUNT(XppParamList );
XPPRET XPPENTRY TRIMQUOTES(XppParamList );
XPPRET XPPENTRY TRIMZ(XppParamList );
XPPRET XPPENTRY C5LTRIM(XppParamList );
XPPRET XPPENTRY C5RTRIM(XppParamList );
XPPRET XPPENTRY C5ALLTRIM(XppParamList );
XPPRET XPPENTRY STRTRIMEX(XppParamList );
XPPRET XPPENTRY LSTRWILDCMPEX(XppParamList );
XPPRET XPPENTRY LSTRWILDCMP(XppParamList );
XPPRET XPPENTRY CDW2BITS(XppParamList );
XPPRET XPPENTRY NBITS2DW(XppParamList );
XPPRET XPPENTRY CGENRNDSTR(XppParamList );
XPPRET XPPENTRY OT4XB_NRAND(XppParamList );
XPPRET XPPENTRY SPLIT_DATA_URI(XppParamList );
XPPRET XPPENTRY OT4XB_REGEX_MATCH(XppParamList );
XPPRET XPPENTRY OT4XB_REGEX_REPLACE(XppParamList );
XPPRET XPPENTRY OT4XB_REGEX_SEARCH(XppParamList );
// _XPP_REG_FUN_(OT4XB_REGEX_EXEC )



// -------- // hex functions

XPPRET XPPENTRY CHEX2BIN(XppParamList );
XPPRET XPPENTRY CBIN2HEX(XppParamList );
XPPRET XPPENTRY CDW2HEX(XppParamList );
XPPRET XPPENTRY NHEX2DW(XppParamList );
XPPRET XPPENTRY CW2HEX(XppParamList );
XPPRET XPPENTRY NHEX2W(XppParamList );
XPPRET XPPENTRY CBYTE2HEX(XppParamList );
XPPRET XPPENTRY NHEX2BYTE(XppParamList );

XPPRET XPPENTRY CQW2HEX(XppParamList );
XPPRET XPPENTRY NHEX2QW(XppParamList );
XPPRET XPPENTRY NHEX2DOUBLE(XppParamList );
XPPRET XPPENTRY CDOUBLE2HEX(XppParamList );

// ------------- encode/decode
XPPRET XPPENTRY __B64ENC(XppParamList );
XPPRET XPPENTRY __B64DEC(XppParamList );

// ---------------------------------------------------------------------------
// ot4xb_json.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB_JSON_PARSE(XppParamList );

// ---------------------------------------------------------------------------
// Unicode.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY CSZANSI2WIDE(XppParamList );
XPPRET XPPENTRY CSZWIDE2ANSI(XppParamList );
XPPRET XPPENTRY UNICODEDYNSTR(XppParamList );
XPPRET XPPENTRY CUTF8TOANSI(XppParamList );
XPPRET XPPENTRY CANSITOUTF8(XppParamList );
XPPRET XPPENTRY CUTF8TOOEM(XppParamList );
XPPRET XPPENTRY COEMTOUTF8(XppParamList );
XPPRET XPPENTRY PEEKWSTR(XppParamList );
XPPRET XPPENTRY CUTF8TOWIDE(XppParamList );
XPPRET XPPENTRY _MB2W(XppParamList );
XPPRET XPPENTRY _W2MB(XppParamList );
XPPRET XPPENTRY _MB2MB(XppParamList );


// ---------------------------------------------------------------------------
// Container.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY TYPE2EMPTYVALUE(XppParamList );
XPPRET XPPENTRY PPMARSHALL2ARRAY(XppParamList );
XPPRET XPPENTRY ARRAY2PPMARSHALL(XppParamList );
XPPRET XPPENTRY PSZZ2ARRAY(XppParamList );
XPPRET XPPENTRY ARRAY2PSZZ(XppParamList );
XPPRET XPPENTRY LCALLFUNCPA(XppParamList );
XPPRET XPPENTRY LCALLMETHODPA(XppParamList );
XPPRET XPPENTRY CALLFUNCTION(XppParamList );
XPPRET XPPENTRY LOBJGETMEMBER(XppParamList );
XPPRET XPPENTRY LOBJSETMEMBER(XppParamList );
XPPRET XPPENTRY _VAR2CON(XppParamList );
XPPRET XPPENTRY _CON2VAR(XppParamList );
XPPRET XPPENTRY _CONRELEASE(XppParamList );
XPPRET XPPENTRY OT4XB_MEMVAR_SETGET(XppParamList );
XPPRET XPPENTRY _CONGENERICBREAKCB(XppParamList );
XPPRET XPPENTRY __VDEF(XppParamList );
XPPRET XPPENTRY __VBLOCK(XppParamList );
XPPRET XPPENTRY __VNUM(XppParamList );
XPPRET XPPENTRY __VLOWER(XppParamList );
XPPRET XPPENTRY __VUPPER(XppParamList );
XPPRET XPPENTRY __VSTR(XppParamList );
XPPRET XPPENTRY __ANEW(XppParamList );
XPPRET XPPENTRY __VCLSPTR(XppParamList );
XPPRET XPPENTRY __VMASK(XppParamList );
XPPRET XPPENTRY __XB_TYPE(XppParamList );
XPPRET XPPENTRY __APEEK(XppParamList );
XPPRET XPPENTRY __VPEEK(XppParamList );
XPPRET XPPENTRY __ANEXT(XppParamList );
XPPRET XPPENTRY __XML_FV(XppParamList );
XPPRET XPPENTRY __XML_FV_GET_VALUE(XppParamList );
XPPRET XPPENTRY __V2FV(XppParamList );
XPPRET XPPENTRY __V2_CSV_CELL(XppParamList );
XPPRET XPPENTRY OT4XB_QLOOP(XppParamList );

XPPRET XPPENTRY __VCMP(XppParamList );

// ---------------------------------------------------------------------------
// ot4xb_vtran.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY __VTRAN(XppParamList );



// ---------------------------------------------------------------------------
// Memory.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY _XGRAB_COUNT_(XppParamList );
XPPRET XPPENTRY _XGRAB(XppParamList );
XPPRET XPPENTRY _XFREE(XppParamList );
XPPRET XPPENTRY _VGRAB(XppParamList );
XPPRET XPPENTRY _VFREE(XppParamList );
XPPRET XPPENTRY _PGRAB(XppParamList );
XPPRET XPPENTRY _PFREE(XppParamList );
XPPRET XPPENTRY _BSET(XppParamList );
XPPRET XPPENTRY _BMOVE(XppParamList );
XPPRET XPPENTRY _BDUP(XppParamList );
XPPRET XPPENTRY _BCOPYWITHTABLE(XppParamList );
XPPRET XPPENTRY _BCOPY(XppParamList );
XPPRET XPPENTRY _BCOPYF(XppParamList );
XPPRET XPPENTRY _BCMP(XppParamList );
XPPRET XPPENTRY _BSCAN(XppParamList );
XPPRET XPPENTRY _XSTRCPY(XppParamList );
XPPRET XPPENTRY _XXSTRCPY(XppParamList );
XPPRET XPPENTRY _XSTCCPY(XppParamList );
XPPRET XPPENTRY _XSTRNCPY(XppParamList );
XPPRET XPPENTRY _XSTRCAT(XppParamList );
XPPRET XPPENTRY _XSTPCHR(XppParamList );
XPPRET XPPENTRY _XSTPBLK(XppParamList );
XPPRET XPPENTRY _XSTRLEN(XppParamList );
XPPRET XPPENTRY _XSTRDUP(XppParamList );
XPPRET XPPENTRY _XSTRAT(XppParamList );
XPPRET XPPENTRY _SHIFT_PTR_(XppParamList );



// ---------------------------------------------------------------------------
// PeekPoke.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY PEEKSTR(XppParamList );
XPPRET XPPENTRY POKESTR(XppParamList );
XPPRET XPPENTRY PEEKBYTE(XppParamList );
XPPRET XPPENTRY POKEBYTE(XppParamList );
XPPRET XPPENTRY PEEKWORD(XppParamList );
XPPRET XPPENTRY PEEKSHORT(XppParamList );
XPPRET XPPENTRY POKEWORD(XppParamList );
XPPRET XPPENTRY PEEKDWORD(XppParamList );
XPPRET XPPENTRY POKEDWORD(XppParamList );
XPPRET XPPENTRY PEEKDOUBLE(XppParamList );
XPPRET XPPENTRY POKEDOUBLE(XppParamList );
XPPRET XPPENTRY PEEKFLOAT(XppParamList );
XPPRET XPPENTRY POKEFLOAT(XppParamList );
XPPRET XPPENTRY PEEKWORDNET(XppParamList );
XPPRET XPPENTRY PEEKDWORDNET(XppParamList );
XPPRET XPPENTRY POKEWORDNET(XppParamList );
XPPRET XPPENTRY POKEDWORDNET(XppParamList );
XPPRET XPPENTRY __I8(XppParamList );
XPPRET XPPENTRY __I16(XppParamList );
XPPRET XPPENTRY __I32(XppParamList );
XPPRET XPPENTRY __F32(XppParamList );
XPPRET XPPENTRY __F64(XppParamList );
XPPRET XPPENTRY PPVTBL2A(XppParamList );
XPPRET XPPENTRY PPVTBL2N(XppParamList );

// ---------------------------------------------------------------------------
// TGXbStack.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY TGXBSTACK(XppParamList );

// ---------------------------------------------------------------------------
// TLXbStack.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY TLSSTACKTOP(XppParamList );
XPPRET XPPENTRY TLSSTACKPUSH(XppParamList );
XPPRET XPPENTRY TLSSTACKPOP(XppParamList );
XPPRET XPPENTRY TLSSTACKCOUNT(XppParamList );
XPPRET XPPENTRY TLS(XppParamList );
XPPRET XPPENTRY WITHOBJECTSTACKTOP(XppParamList );
XPPRET XPPENTRY WITHOBJECTSTACKPUSH(XppParamList );
XPPRET XPPENTRY WITHOBJECTSTACKPOP(XppParamList );
XPPRET XPPENTRY WITHOBJECTSTACKCOUNT(XppParamList );
XPPRET XPPENTRY WITHOBJECTSTACKRECOVER(XppParamList );

XPPRET XPPENTRY XBTLSALLOC(XppParamList );
XPPRET XPPENTRY XBTLSFREE(XppParamList );
XPPRET XPPENTRY XBTLSSETVALUE(XppParamList );
XPPRET XPPENTRY XBTLSGETVALUE(XppParamList );

XPPRET XPPENTRY OT4XB_ARRAY_ITERATOR(XppParamList );
XPPRET XPPENTRY OT4XB_ARRAY_ITERATOR_STEP(XppParamList );
XPPRET XPPENTRY OT4XB_ARRAY_ITERATOR_INDEX(XppParamList );

// ---------------------------------------------------------------------------
// gwst.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY GWST(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_BOOL_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_BYTEBOOL_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_BYTE_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_SINT8_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_WORD_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_SINT16_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_DWORD_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_UINT32_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_DWORD64_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_NINT64_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_PCLIPVAR_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_XPPGUIWND_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_FLOAT_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_DOUBLE_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_LPSTR_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_BINSTR_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_SZSTR_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_SZWSTR_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_DYNSZ_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_WORDNET_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_DWORDNET_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_XDATE_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_POINTER32_(XppParamList );
XPPRET XPPENTRY _GWST_XBSETGET_HANDLE_(XppParamList );
// ---------------------------------------------------------------------------
// XbClass
// ---------------------------------------------------------------------------
XPPRET XPPENTRY _XBMTPF1_(XppParamList );
XPPRET XPPENTRY TXBCLASS(XppParamList );

// ---------------------------------------------------------------------------
// Num64.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY LONGLONG2DOUBLE(XppParamList );
XPPRET XPPENTRY DOUBLE2LONGLONG(XppParamList );
XPPRET XPPENTRY ULONGLONG2DOUBLE(XppParamList );
XPPRET XPPENTRY DOUBLE2ULONGLONG(XppParamList );
XPPRET XPPENTRY GETNUMFORMAT(XppParamList );
XPPRET XPPENTRY LISNUMF64(XppParamList );
XPPRET XPPENTRY SETNUMFORMAT(XppParamList );
XPPRET XPPENTRY _LARGE_INTEGER_(XppParamList );
XPPRET XPPENTRY wapist_LARGE_INTEGER(XppParamList );
XPPRET XPPENTRY wapist_ULARGE_INTEGER(XppParamList );
XPPRET XPPENTRY MAKE_QWORD(XppParamList );
XPPRET XPPENTRY MAKE_INT64(XppParamList );
XPPRET XPPENTRY LO_DWORD(XppParamList );
XPPRET XPPENTRY HI_DWORD(XppParamList );
XPPRET XPPENTRY I64CMP(XppParamList );
XPPRET XPPENTRY I64SUM(XppParamList );
XPPRET XPPENTRY I64REST(XppParamList );
XPPRET XPPENTRY I64MULT(XppParamList );
XPPRET XPPENTRY I64DIV(XppParamList );
XPPRET XPPENTRY I64MOD(XppParamList );



// ---------------------------------------------------------------------------
// uuid.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY _UUIDCREATE(XppParamList );
XPPRET XPPENTRY UUIDCREATESTR(XppParamList );
XPPRET XPPENTRY CUUIDCREATENAME(XppParamList );
XPPRET XPPENTRY CUUIDCREATENAMEEX(XppParamList );
XPPRET XPPENTRY UUIDFROMSTRING(XppParamList );
XPPRET XPPENTRY UUIDTOSTRING(XppParamList );


// ---------------------------------------------------------------------------
// fpCall.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY SET_FPCALL_FLAGS(XppParamList );
XPPRET XPPENTRY _DUMMYSTDCBK(XppParamList );
XPPRET XPPENTRY NLOADLIBRARY(XppParamList );
XPPRET XPPENTRY LFREELIBRARY(XppParamList );
XPPRET XPPENTRY _FPCALL_PUSHFLAGS_(XppParamList );
XPPRET XPPENTRY NFPCALL(XppParamList );
XPPRET XPPENTRY NFPGET(XppParamList );
XPPRET XPPENTRY F2T(XppParamList );
XPPRET XPPENTRY XBFPCALL(XppParamList );
XPPRET XPPENTRY NDFPCALL(XppParamList );
XPPRET XPPENTRY QWFPCALL(XppParamList );
XPPRET XPPENTRY NFPGETLASTERROR(XppParamList );
XPPRET XPPENTRY QFPGETLASTPOINTER(XppParamList );
XPPRET XPPENTRY QFPSETLASTPOINTER(XppParamList );
XPPRET XPPENTRY NGETPROCADDRESS(XppParamList );
XPPRET XPPENTRY FPQCALL(XppParamList );
XPPRET XPPENTRY IFPQCALL(XppParamList );
XPPRET XPPENTRY FPLQCALL2(XppParamList );
XPPRET XPPENTRY FPLQCALL(XppParamList );
XPPRET XPPENTRY OT4XB_GENERIC_POINTER(XppParamList );
XPPRET XPPENTRY PT2GP(XppParamList );
XPPRET XPPENTRY CPRINTF(XppParamList );
XPPRET XPPENTRY __PRINTF(XppParamList );
XPPRET XPPENTRY LWRITELOGLINE(XppParamList );
XPPRET XPPENTRY LSENDLOGSTRFL(XppParamList );
XPPRET XPPENTRY LSENDLOGSTR(XppParamList );
XPPRET XPPENTRY REGISTER_USER_LOG_UUID(XppParamList );
XPPRET XPPENTRY OT4XB_LSENDLOGSTRFL(XppParamList );
XPPRET XPPENTRY OT4XB_LSENDLOGSTR(XppParamList );
XPPRET XPPENTRY CFMTRESMSG(XppParamList );
XPPRET XPPENTRY CFMTSTRMSG(XppParamList );
XPPRET XPPENTRY CFMTSYSMSG(XppParamList );




// ---------------------------------------------------------------------------
// TBinFile.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY LMEMOWRITE(XppParamList );
XPPRET XPPENTRY CMEMOREADEX(XppParamList );
XPPRET XPPENTRY TBINFILE(XppParamList );
XPPRET XPPENTRY TFILEWRITER(XppParamList );

XPPRET XPPENTRY LMEMOSTGWRITE(XppParamList );
XPPRET XPPENTRY CMEMOSTGREAD(XppParamList );
XPPRET XPPENTRY LMEMOSTGEXPORT(XppParamList );
XPPRET XPPENTRY LMEMOSTGIMPORT(XppParamList );
XPPRET XPPENTRY CMEMOSTGLIST(XppParamList );

// ---------------------------------------------------------------------------
// FileTime.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY wapist_FILETIME64(XppParamList );
XPPRET XPPENTRY FT64_SETTS(XppParamList );
XPPRET XPPENTRY FT64_GETTS(XppParamList );
XPPRET XPPENTRY FT64_TOHTTP(XppParamList );
XPPRET XPPENTRY FT64_SETDATETIME(XppParamList );
XPPRET XPPENTRY FT64_GETDATETIME(XppParamList );
XPPRET XPPENTRY FT64_GETDATETIMESEC(XppParamList );
XPPRET XPPENTRY FT64_NOW(XppParamList );
XPPRET XPPENTRY FT64_ELAPMILLISECONDS(XppParamList );
XPPRET XPPENTRY FT64_ELAPSECONDS(XppParamList );
XPPRET XPPENTRY FT64_COMPARE(XppParamList );
XPPRET XPPENTRY FT64_ADD(XppParamList );
XPPRET XPPENTRY FT64_ADD_Y(XppParamList );
XPPRET XPPENTRY FT64_ADD_M(XppParamList );
XPPRET XPPENTRY FT64_TO_DOSDATETIME(XppParamList );
XPPRET XPPENTRY FT64_FROM_DOSDATETIME(XppParamList );
XPPRET XPPENTRY FT64_TO_UNIXTIME(XppParamList );
XPPRET XPPENTRY FT64_FROM_UNIXTIME(XppParamList );
XPPRET XPPENTRY FT64_TO_EXCELTIME(XppParamList );
XPPRET XPPENTRY FT64_FROM_EXCELTIME(XppParamList );
XPPRET XPPENTRY DT2ISO8601(XppParamList );
XPPRET XPPENTRY FT64_SETRFC822DATE(XppParamList );
XPPRET XPPENTRY FT64_TOLOCALTIME(XppParamList );
XPPRET XPPENTRY FT64_STRF(XppParamList );
XPPRET XPPENTRY FT64_GET_CKF32TS(XppParamList );
XPPRET XPPENTRY FT64_SET_CKF32TS(XppParamList );



// ---------------------------------------------------------------------------
// THashTable.cpp
// ---------------------------------------------------------------------------

XPPRET XPPENTRY _HDICT_NEW(XppParamList );
XPPRET XPPENTRY _HDICT_KEY_COMPARE(XppParamList );
XPPRET XPPENTRY _HDICT_DESTROY(XppParamList );
XPPRET XPPENTRY _HDICT_SETPROP(XppParamList );
XPPRET XPPENTRY _HDICT_GETPROP(XppParamList );
XPPRET XPPENTRY _HDICT_ISPROP(XppParamList );
XPPRET XPPENTRY _HDICT_GETPROP_RAW_(XppParamList );

XPPRET XPPENTRY _HDICT_REMOVEPROP(XppParamList );
XPPRET XPPENTRY _HDICT_REMOVEALL(XppParamList );
XPPRET XPPENTRY _HDICT_COUNT(XppParamList );
XPPRET XPPENTRY _HDICT_ITERATE_STEP(XppParamList );
XPPRET XPPENTRY _HDICT_ITERATE_CB(XppParamList );
XPPRET XPPENTRY _HDICT_ADDPROPFROMARRAY(XppParamList );
XPPRET XPPENTRY _HDICT_ADDPROPFROMINISTRING(XppParamList );
XPPRET XPPENTRY _HDICT_ADD_ENV_STRINGS(XppParamList );
XPPRET XPPENTRY _HDICT_ADD_HTTP_HEADERS(XppParamList );
XPPRET XPPENTRY _HDICT_FROM_ZKDW(XppParamList );
// -------------
XPPRET XPPENTRY THDICTEX(XppParamList );

// -------------
XPPRET XPPENTRY OT4XB_HASH(XppParamList );
XPPRET XPPENTRY OT4XB_CNG(XppParamList );

XPPRET XPPENTRY ARGON2_HASH(XppParamList );
XPPRET XPPENTRY ARGON2_VERIFY(XppParamList );

// ------------- case sensitive hash table
XPPRET XPPENTRY _HDICTCS_COUNT(XppParamList );
XPPRET XPPENTRY _HDICTCS_DESTROY(XppParamList );
XPPRET XPPENTRY _HDICTCS_GETPROP(XppParamList );
XPPRET XPPENTRY _HDICTCS_ISPROP(XppParamList );
XPPRET XPPENTRY _HDICTCS_KEY_COMPARE(XppParamList );
XPPRET XPPENTRY _HDICTCS_NEW(XppParamList );
XPPRET XPPENTRY _HDICTCS_REMOVEALL(XppParamList );
XPPRET XPPENTRY _HDICTCS_REMOVEPROP(XppParamList );
XPPRET XPPENTRY _HDICTCS_SETPROP(XppParamList );

// ---------------------------------------------------------------------------
// OT4XB_EXPANDO.CPP
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB_ITERATE_ARRAY_CB(XppParamList );
XPPRET XPPENTRY _OT4XB_EXPANDO_(XppParamList );

// ---------------------------------------------------------------------------
// MD5.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY STR2MD5HEX(XppParamList );
XPPRET XPPENTRY STR2MD5BIN(XppParamList );
XPPRET XPPENTRY HFILE2MD5HEX(XppParamList );
XPPRET XPPENTRY HFILE2MD5BIN(XppParamList );
XPPRET XPPENTRY FILE2MD5HEX(XppParamList );
XPPRET XPPENTRY FILE2MD5BIN(XppParamList );
XPPRET XPPENTRY _MD5_NEW(XppParamList );
XPPRET XPPENTRY _MD5_STR(XppParamList );
XPPRET XPPENTRY _MD5_HFILE(XppParamList );
XPPRET XPPENTRY _MD5_FINALIZE(XppParamList );
XPPRET XPPENTRY _MD5_GETHEX(XppParamList );
XPPRET XPPENTRY _MD5_GETBIN(XppParamList );
XPPRET XPPENTRY _MD5_DESTROY(XppParamList );

// ---------------------------------------------------------------------------
// gdipus_helper.cpp
// ---------------------------------------------------------------------------

XPPRET XPPENTRY GDIPLUS_HELPER(XppParamList );

// ---------------------------------------------------------------------------
// array2dbf.cpp
// ---------------------------------------------------------------------------

XPPRET XPPENTRY _A2DBF_(XppParamList );

// ---------------------------------------------------------------------------
// ot4xb_IUnknow.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB_IUNKNOW(XppParamList );
XPPRET XPPENTRY OT4XB_IDISPATCH(XppParamList );
XPPRET XPPENTRY OT4XB_ISEQUENTIALSTREAM(XppParamList );
XPPRET XPPENTRY OT4XB_ISTREAM(XppParamList );


// ---------------------------------------------------------------------------
// ot4xb_ndtg.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY NDTG_CREATE_TYPEDEF_TABLE(XppParamList );
XPPRET XPPENTRY NDTG_DESTROY_TYPEDEF_TABLE(XppParamList );
XPPRET XPPENTRY NDTG_ADD_TYPE(XppParamList );
XPPRET XPPENTRY NDTG_SET_ATTRIB_CB(XppParamList );
XPPRET XPPENTRY NDTG_GET_TYPE(XppParamList );
XPPRET XPPENTRY NDTG_ADD_PROP(XppParamList );
XPPRET XPPENTRY NDTG_STACK_BEGIN(XppParamList );
XPPRET XPPENTRY NDTG_STACK_STEP(XppParamList );
XPPRET XPPENTRY NDTG_STACK_SEAL(XppParamList );
XPPRET XPPENTRY NDTG_STACK_UNSEALED(XppParamList );
XPPRET XPPENTRY NDTG_STACK_PUTVAL(XppParamList );
XPPRET XPPENTRY NDTG_STACK_ATTRIB(XppParamList );
XPPRET XPPENTRY NDTG_STACK_ATTRIB_SEAL(XppParamList );
XPPRET XPPENTRY NDTG_STACK_END(XppParamList );


// ---------------------------------------------------------------------------
// ot4xb_iocp.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB_IOCP(XppParamList );


// ---------------------------------------------------------------------------
// ot4xb_dirty_dlgedit.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY OT4XB_DIRTY_DLGEDIT(XppParamList );


// ---------------------------------------------------------------------------
// ot4xb_disphelper.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY _DH_CREATEOBJECT(XppParamList );
XPPRET XPPENTRY _DH_GETOBJECT(XppParamList );
XPPRET XPPENTRY _DH_CREATEOBJECTEX(XppParamList );
XPPRET XPPENTRY _DH_GETOBJECTEX(XppParamList );
XPPRET XPPENTRY _DH_CALLMETHOD(XppParamList );
XPPRET XPPENTRY _DH_PUTVALUE(XppParamList );
XPPRET XPPENTRY _DH_PUTREF(XppParamList );
XPPRET XPPENTRY _DH_GETVALUE(XppParamList );
XPPRET XPPENTRY _DH_INVOKE(XppParamList );
XPPRET XPPENTRY _DH_INVOKEARRAY(XppParamList );
XPPRET XPPENTRY _DH_CALLMETHODV(XppParamList );
XPPRET XPPENTRY _DH_PUTVALUEV(XppParamList );
XPPRET XPPENTRY _DH_PUTREFV(XppParamList );
XPPRET XPPENTRY _DH_GETVALUEV(XppParamList );
XPPRET XPPENTRY _DH_INVOKEV(XppParamList );
XPPRET XPPENTRY _DH_ENUMBEGIN(XppParamList );
XPPRET XPPENTRY _DH_ENUMBEGINV(XppParamList );
XPPRET XPPENTRY _DH_ENUMNEXTOBJECT(XppParamList );
XPPRET XPPENTRY _DH_ENUMNEXTVARIANT(XppParamList );
XPPRET XPPENTRY _DH_TOGGLEEXCEPTIONS(XppParamList );


// ---------------------------------------------------------------------------
// ot4xb_regexp.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY _RGX(XppParamList );
XPPRET XPPENTRY _RGX_NEW(XppParamList );
XPPRET XPPENTRY _RGX_SET_PATTERN(XppParamList );
XPPRET XPPENTRY _RGX_SET_FLAGS(XppParamList );
XPPRET XPPENTRY _RGX_DESTROY(XppParamList );
XPPRET XPPENTRY _RGX_EXEC(XppParamList );
XPPRET XPPENTRY _RGX_TEST(XppParamList );
XPPRET XPPENTRY _RGX_REPLACE(XppParamList );

// _XPP_REG_FUN_( _STRING_MAP_TABLE         )
// _XPP_REG_FUN_( _STRING_MAP_TABLE_NEW     )
// _XPP_REG_FUN_( _STRING_MAP_TABLE_DESTROY )
// _XPP_REG_FUN_( _STRING_MAP_TABLE_EXEC    )

// ---------------------------------------------------------------------------
// ot4xb_sqlstr.cpp
// ---------------------------------------------------------------------------
XPPRET XPPENTRY __SQLSTR_MONEY(XppParamList );
XPPRET XPPENTRY __SQLSTR_MONEY_SUM(XppParamList );
XPPRET XPPENTRY __SQLSTR_MONEY_SUBSTRACT(XppParamList );
// ------
XPPRET XPPENTRY OT4XB_SQL_ESCAPE_STRING_ANSI(XppParamList );
XPPRET XPPENTRY OT4XB_SQL_DUMP_VALUE_ANSI(XppParamList );
XPPRET XPPENTRY OT4XB_GET_SQL_TYPE_FLAG_ENUM(XppParamList );
XPPRET XPPENTRY OT4XB_GET_SQL_TYPE_ENUM(XppParamList );
XPPRET XPPENTRY OT4XB_GET_SQL_TYPE_LEN(XppParamList );
XPPRET XPPENTRY OT4XB_GET_SQL_TYPE_DEC(XppParamList );




// ---------------------------------------------------------------------------
// TPeFile.cpp
// ---------------------------------------------------------------------------
// ---------- _XPP_REG_FUN_( TPEFILE )

// ---------------------------------------------------------------------------
// common windows structures
// ---------------------------------------------------------------------------
XPPRET XPPENTRY WAPIST__PRINTER_NOTIFY_INFO_DATA___DATA(XppParamList );
XPPRET XPPENTRY WAPIST__PRINTER_NOTIFY_INFO_DATA___NOTIFYDATA(XppParamList );
XPPRET XPPENTRY WAPIST_ABC(XppParamList );
XPPRET XPPENTRY WAPIST_ABCFLOAT(XppParamList );
XPPRET XPPENTRY WAPIST_ACCEL(XppParamList );
XPPRET XPPENTRY WAPIST_ADDJOB_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_ALTTABINFO(XppParamList );
XPPRET XPPENTRY WAPIST_BIDIOPTIONS(XppParamList );
XPPRET XPPENTRY WAPIST_BITMAP(XppParamList );
XPPRET XPPENTRY WAPIST_BITMAPINFO(XppParamList );
XPPRET XPPENTRY WAPIST_BITMAPINFOHEADER(XppParamList );
XPPRET XPPENTRY WAPIST_BLENDFUNCTION(XppParamList );
XPPRET XPPENTRY WAPIST_CHARFORMAT(XppParamList );
XPPRET XPPENTRY WAPIST_CHARFORMAT2(XppParamList );
XPPRET XPPENTRY WAPIST_CHARRANGE(XppParamList );
XPPRET XPPENTRY WAPIST_CLSID(XppParamList );
XPPRET XPPENTRY WAPIST_COMPCOLOR(XppParamList );
XPPRET XPPENTRY WAPIST_CURSORINFO(XppParamList );
XPPRET XPPENTRY WAPIST_DATATYPES_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_DEVMODE(XppParamList );
XPPRET XPPENTRY WAPIST_DIBSECTION(XppParamList );
XPPRET XPPENTRY WAPIST_DLGITEMTEMPLATE(XppParamList );
XPPRET XPPENTRY WAPIST_DLGTEMPLATE(XppParamList );
XPPRET XPPENTRY WAPIST_DOC_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_DOC_INFO_2(XppParamList );
XPPRET XPPENTRY WAPIST_DOC_INFO_3(XppParamList );
XPPRET XPPENTRY WAPIST_DOCINFO(XppParamList );
XPPRET XPPENTRY WAPIST_DRAWPATRECT(XppParamList );
XPPRET XPPENTRY WAPIST_DRAWTEXTPARAMS(XppParamList );
XPPRET XPPENTRY WAPIST_DRIVER_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_DRIVER_INFO_2(XppParamList );
XPPRET XPPENTRY WAPIST_DRIVER_INFO_3(XppParamList );
XPPRET XPPENTRY WAPIST_DRIVER_INFO_4(XppParamList );
XPPRET XPPENTRY WAPIST_DRIVER_INFO_5(XppParamList );
XPPRET XPPENTRY WAPIST_DRIVER_INFO_6(XppParamList );
XPPRET XPPENTRY WAPIST_EDITSTREAM(XppParamList );
XPPRET XPPENTRY WAPIST_ENCORRECTTEXT(XppParamList );
XPPRET XPPENTRY WAPIST_ENDROPFILES(XppParamList );
XPPRET XPPENTRY WAPIST_ENLINK(XppParamList );
XPPRET XPPENTRY WAPIST_ENLOWFIRTF(XppParamList );
XPPRET XPPENTRY WAPIST_ENOLEOPFAILED(XppParamList );
XPPRET XPPENTRY WAPIST_ENPROTECTED(XppParamList );
XPPRET XPPENTRY WAPIST_ENSAVECLIPBOARD(XppParamList );
XPPRET XPPENTRY WAPIST_ENUMLOGFONT(XppParamList );
XPPRET XPPENTRY WAPIST_ENUMLOGFONTEX(XppParamList );
XPPRET XPPENTRY WAPIST_EXTLOGFONT(XppParamList );
XPPRET XPPENTRY WAPIST_EXTLOGPEN(XppParamList );
XPPRET XPPENTRY WAPIST_FINDTEXT(XppParamList );
XPPRET XPPENTRY WAPIST_FINDTEXTEX(XppParamList );
XPPRET XPPENTRY WAPIST_FIXED(XppParamList );
XPPRET XPPENTRY WAPIST_FLASHWINFO(XppParamList );
XPPRET XPPENTRY WAPIST_FONTSIGNATURE(XppParamList );
XPPRET XPPENTRY WAPIST_FORM_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_FORMATRANGE(XppParamList );
XPPRET XPPENTRY WAPIST_GCP_RESULTS(XppParamList );
XPPRET XPPENTRY WAPIST_GETTEXTEX(XppParamList );
XPPRET XPPENTRY WAPIST_GETTEXTLENGTHEX(XppParamList );
XPPRET XPPENTRY WAPIST_GLYPHMETRICS(XppParamList );
XPPRET XPPENTRY WAPIST_GLYPHSET(XppParamList );
XPPRET XPPENTRY WAPIST_GUID(XppParamList );
XPPRET XPPENTRY WAPIST_GUITHREADINFO(XppParamList );
XPPRET XPPENTRY WAPIST_HARDWAREINPUT(XppParamList );
XPPRET XPPENTRY WAPIST_HYPHENATEINFO(XppParamList );
XPPRET XPPENTRY WAPIST_HYPHRESULT(XppParamList );
XPPRET XPPENTRY WAPIST_ICONINFO(XppParamList );
XPPRET XPPENTRY WAPIST_ICONMETRICS(XppParamList );
XPPRET XPPENTRY WAPIST_IMAGEINFO(XppParamList );
XPPRET XPPENTRY WAPIST_IMAGELISTDRAWPARAMS(XppParamList );
XPPRET XPPENTRY WAPIST_IMECOMPTEXT(XppParamList );
XPPRET XPPENTRY WAPIST_INPUT(XppParamList );
XPPRET XPPENTRY WAPIST_JOB_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_JOB_INFO_2(XppParamList );
XPPRET XPPENTRY WAPIST_JOB_INFO_3(XppParamList );
XPPRET XPPENTRY WAPIST_KERNINGPAIR(XppParamList );
XPPRET XPPENTRY WAPIST_KEYBDINPUT(XppParamList );
XPPRET XPPENTRY WAPIST_LASTINPUTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_LOGBRUSH(XppParamList );
XPPRET XPPENTRY WAPIST_LOGBRUSH32(XppParamList );
XPPRET XPPENTRY WAPIST_LOGFONT(XppParamList );
XPPRET XPPENTRY WAPIST_LOGPALETTE(XppParamList );
XPPRET XPPENTRY WAPIST_LOGPEN(XppParamList );
XPPRET XPPENTRY WAPIST_MAT2(XppParamList );
XPPRET XPPENTRY WAPIST_MDICREATESTRUCT(XppParamList );
XPPRET XPPENTRY WAPIST_MDINEXTMENU(XppParamList );
XPPRET XPPENTRY WAPIST_MENUBARINFO(XppParamList );
XPPRET XPPENTRY WAPIST_MENUEX_TEMPLATE_HEADER(XppParamList );
XPPRET XPPENTRY WAPIST_MENUEX_TEMPLATE_ITEM(XppParamList );
XPPRET XPPENTRY WAPIST_MENUGETOBJECTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_MENUINFO(XppParamList );
XPPRET XPPENTRY WAPIST_MENUITEMINFO(XppParamList );
XPPRET XPPENTRY WAPIST_MENUITEMTEMPLATE(XppParamList );
XPPRET XPPENTRY WAPIST_MENUITEMTEMPLATEHEADER(XppParamList );
XPPRET XPPENTRY WAPIST_METAFILEPICT(XppParamList );
XPPRET XPPENTRY WAPIST_MINMAXINFO(XppParamList );
XPPRET XPPENTRY WAPIST_MONITOR_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_MONITOR_INFO_2(XppParamList );
XPPRET XPPENTRY WAPIST_MONITORINFO(XppParamList );
XPPRET XPPENTRY WAPIST_MONITORINFOEX(XppParamList );
XPPRET XPPENTRY WAPIST_MOUSEINPUT(XppParamList );
XPPRET XPPENTRY WAPIST_MSG(XppParamList );
XPPRET XPPENTRY WAPIST_MSGBOXPARAMS(XppParamList );
XPPRET XPPENTRY WAPIST_MSGFILTER(XppParamList );
XPPRET XPPENTRY WAPIST_NEWTEXTMETRIC(XppParamList );
XPPRET XPPENTRY WAPIST_NEWTEXTMETRICEX(XppParamList );
XPPRET XPPENTRY WAPIST_NMHDR(XppParamList );
XPPRET XPPENTRY WAPIST_NMRBAUTOSIZE(XppParamList );
XPPRET XPPENTRY WAPIST_NMREBAR(XppParamList );
XPPRET XPPENTRY WAPIST_NMREBARAUTOBREAK(XppParamList );
XPPRET XPPENTRY WAPIST_NMREBARCHEVRON(XppParamList );
XPPRET XPPENTRY WAPIST_NMREBARCHILDSIZE(XppParamList );
XPPRET XPPENTRY WAPIST_OBJECTPOSITIONS(XppParamList );
XPPRET XPPENTRY WAPIST_OUTLINETEXTMETRIC(XppParamList );
XPPRET XPPENTRY WAPIST_PAINTSTRUCT(XppParamList );
XPPRET XPPENTRY WAPIST_PALETTEENTRY(XppParamList );
XPPRET XPPENTRY WAPIST_PANOSE(XppParamList );
XPPRET XPPENTRY WAPIST_PARAFORMAT(XppParamList );
XPPRET XPPENTRY WAPIST_PARAFORMAT2(XppParamList );
XPPRET XPPENTRY WAPIST_POINT(XppParamList );
XPPRET XPPENTRY WAPIST_POINTFX(XppParamList );
XPPRET XPPENTRY WAPIST_POINTL(XppParamList );
XPPRET XPPENTRY WAPIST_POINTS(XppParamList );
XPPRET XPPENTRY WAPIST_POLYTEXT(XppParamList );
XPPRET XPPENTRY WAPIST_PORT_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_PORT_INFO_2(XppParamList );
XPPRET XPPENTRY WAPIST_PORT_INFO_3(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_DEFAULTS(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_ENUM_VALUES(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_2(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_3(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_4(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_5(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_6(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_7(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_8(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_INFO_9(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_NOTIFY_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_NOTIFY_INFO_DATA(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_NOTIFY_OPTIONS(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTER_NOTIFY_OPTIONS_TYPE(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTPROCESSOR_CAPS_1(XppParamList );
XPPRET XPPENTRY WAPIST_PRINTPROCESSOR_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_PROVIDOR_INFO_1(XppParamList );
XPPRET XPPENTRY WAPIST_PROVIDOR_INFO_2(XppParamList );
XPPRET XPPENTRY WAPIST_PSFEATURE_CUSTPAPER(XppParamList );
XPPRET XPPENTRY WAPIST_PSFEATURE_OUTPUT(XppParamList );
XPPRET XPPENTRY WAPIST_PSINJECTDATA(XppParamList );
XPPRET XPPENTRY WAPIST_PUNCTUATION(XppParamList );
XPPRET XPPENTRY WAPIST_RASTERIZER_STATUS(XppParamList );
XPPRET XPPENTRY WAPIST_RBHITTESTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_REBARBANDINFO(XppParamList );
XPPRET XPPENTRY WAPIST_REBARINFO(XppParamList );
XPPRET XPPENTRY WAPIST_RECT(XppParamList );
XPPRET XPPENTRY WAPIST_RECTL(XppParamList );
XPPRET XPPENTRY WAPIST_REOBJECT(XppParamList );
XPPRET XPPENTRY WAPIST_REPASTESPECIAL(XppParamList );
XPPRET XPPENTRY WAPIST_REQRESIZE(XppParamList );
XPPRET XPPENTRY WAPIST_RGBQUAD(XppParamList );
XPPRET XPPENTRY WAPIST_RGNDATA(XppParamList );
XPPRET XPPENTRY WAPIST_RGNDATAHEADER(XppParamList );
XPPRET XPPENTRY WAPIST_SELCHANGE(XppParamList );
XPPRET XPPENTRY WAPIST_SETTEXTEX(XppParamList );
XPPRET XPPENTRY WAPIST_SIZE(XppParamList );
XPPRET XPPENTRY WAPIST_SIZEL(XppParamList );
XPPRET XPPENTRY WAPIST_SYSTEMTIME(XppParamList );
XPPRET XPPENTRY WAPIST_TBBUTTON(XppParamList );
XPPRET XPPENTRY WAPIST_TEXTMETRIC(XppParamList );
XPPRET XPPENTRY WAPIST_TEXTRANGE(XppParamList );
XPPRET XPPENTRY WAPIST_TITLEBARINFO(XppParamList );
XPPRET XPPENTRY WAPIST_TPMPARAMS(XppParamList );
XPPRET XPPENTRY WAPIST_TRIVERTEX(XppParamList );
XPPRET XPPENTRY WAPIST_TTPOLYCURVE(XppParamList );
XPPRET XPPENTRY WAPIST_TTPOLYGONHEADER(XppParamList );
XPPRET XPPENTRY WAPIST_WCRANGE(XppParamList );
XPPRET XPPENTRY WAPIST_WINDOWINFO(XppParamList );
XPPRET XPPENTRY WAPIST_WINDOWPLACEMENT(XppParamList );
XPPRET XPPENTRY WAPIST_WNDCLASS(XppParamList );
XPPRET XPPENTRY WAPIST_WNDCLASSEX(XppParamList );
XPPRET XPPENTRY WAPIST_XFORM(XppParamList );
// ---
XPPRET XPPENTRY WAPIST_IN_ADDR(XppParamList );
XPPRET XPPENTRY WAPIST_SOCKADDR(XppParamList );
XPPRET XPPENTRY WAPIST_SOCKET_ADDRESS(XppParamList );
XPPRET XPPENTRY WAPIST_SOCKET_ADDRESS_LIST(XppParamList );
XPPRET XPPENTRY WAPIST_CSADDR_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_SOCKADDR_STORAGE(XppParamList );
XPPRET XPPENTRY WAPIST_SCOPE_ID(XppParamList );
XPPRET XPPENTRY WAPIST_SOCKADDR_IN(XppParamList );
XPPRET XPPENTRY WAPIST_WSABUF(XppParamList );
XPPRET XPPENTRY WAPIST_WSAMSG(XppParamList );
XPPRET XPPENTRY WAPIST_WSACMSGHDR(XppParamList );
XPPRET XPPENTRY WAPIST_FD_SET(XppParamList );
XPPRET XPPENTRY WAPIST_TIMEVAL(XppParamList );
XPPRET XPPENTRY WAPIST_HOSTENT(XppParamList );
XPPRET XPPENTRY WAPIST_NETENT(XppParamList );
XPPRET XPPENTRY WAPIST_SERVENT(XppParamList );
XPPRET XPPENTRY WAPIST_PROTOENT(XppParamList );
XPPRET XPPENTRY WAPIST_WSADATA(XppParamList );
XPPRET XPPENTRY WAPIST_SOCKPROTO(XppParamList );
XPPRET XPPENTRY WAPIST_LINGER(XppParamList );
XPPRET XPPENTRY WAPIST_FLOWSPEC(XppParamList );
XPPRET XPPENTRY WAPIST_QOS_OBJECT_HDR(XppParamList );
XPPRET XPPENTRY WAPIST_QOS_SD_MODE(XppParamList );
XPPRET XPPENTRY WAPIST_QOS_SHAPING_RATE(XppParamList );
XPPRET XPPENTRY WAPIST_QOS(XppParamList );
XPPRET XPPENTRY WAPIST_WSANETWORKEVENTS(XppParamList );
XPPRET XPPENTRY WAPIST_WSAPROTOCOLCHAIN(XppParamList );
XPPRET XPPENTRY WAPIST_WSAPROTOCOL_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_WSACOMPLETION_NS_WINDOWMESSAGE(XppParamList );
XPPRET XPPENTRY WAPIST_WSACOMPLETION_NS_EVENT(XppParamList );
XPPRET XPPENTRY WAPIST_WSACOMPLETION_NS_APC(XppParamList );
XPPRET XPPENTRY WAPIST_WSACOMPLETION_NS_PORT(XppParamList );
XPPRET XPPENTRY WAPIST_WSACOMPLETION_NS_PARAMETERS(XppParamList );
XPPRET XPPENTRY WAPIST_WSACOMPLETION(XppParamList );
XPPRET XPPENTRY WAPIST_BLOB(XppParamList );
XPPRET XPPENTRY WAPIST_AFPROTOCOLS(XppParamList );
XPPRET XPPENTRY WAPIST_WSAVERSION(XppParamList );
XPPRET XPPENTRY WAPIST_WSAQUERYSET(XppParamList );
XPPRET XPPENTRY WAPIST_WSAQUERYSET2(XppParamList );
XPPRET XPPENTRY WAPIST_WSANSCLASSINFO(XppParamList );
XPPRET XPPENTRY WAPIST_WSASERVICECLASSINFO(XppParamList );
XPPRET XPPENTRY WAPIST_WSANAMESPACE_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_WSANAMESPACE_INFOEX(XppParamList );
XPPRET XPPENTRY WAPIST_WSAPOLLFD(XppParamList );
XPPRET XPPENTRY WAPIST_ADDRINFO(XppParamList );

XPPRET XPPENTRY WAPIST_OPENFILENAME(XppParamList );
// --------------------------------------
XPPRET XPPENTRY WAPIST_RAWHID(XppParamList );
XPPRET XPPENTRY WAPIST_RAWINPUT_DATA_UNION(XppParamList );
XPPRET XPPENTRY WAPIST_RAWINPUT(XppParamList );
XPPRET XPPENTRY WAPIST_RAWINPUTDEVICE(XppParamList );
XPPRET XPPENTRY WAPIST_RAWINPUTDEVICELIST(XppParamList );
XPPRET XPPENTRY WAPIST_RAWINPUTHEADER(XppParamList );
XPPRET XPPENTRY WAPIST_RAWKEYBOARD(XppParamList );
XPPRET XPPENTRY WAPIST_RAWMOUSE(XppParamList );
XPPRET XPPENTRY WAPIST_RID_DEVICE_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_RID_DEVICE_INFO_HID(XppParamList );
XPPRET XPPENTRY WAPIST_RID_DEVICE_INFO_KEYBOARD(XppParamList );
XPPRET XPPENTRY WAPIST_RID_DEVICE_INFO_MOUSE(XppParamList );
// --------------------------------------


XPPRET XPPENTRY WAPIST_IP_ADDR_STRING(XppParamList );
XPPRET XPPENTRY WAPIST_IP_ADAPTER_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_IP_PER_ADAPTER_INFO(XppParamList );

// --------------------------------------
XPPRET XPPENTRY WAPIST_OVERLAPPED(XppParamList );
XPPRET XPPENTRY WAPIST_SYSTEM_INFO(XppParamList );
// --------------------------------------
XPPRET XPPENTRY WAPIST_OSVERSIONINFOEX(XppParamList );
// --------------------------------------



// --------------------------------------
// TOOLHELP STRUCTURES
// --------------------------------------
XPPRET XPPENTRY WAPIST_MODULEENTRY32(XppParamList );
XPPRET XPPENTRY WAPIST_PROCESSENTRY32(XppParamList );
XPPRET XPPENTRY WAPIST_THREADENTRY32(XppParamList );
XPPRET XPPENTRY WAPIST_HEAPENTRY32(XppParamList );
XPPRET XPPENTRY WAPIST_HEAPLIST32(XppParamList );

// ----------------------------------------
// common controls - listview support
// ----------------------------------------
XPPRET XPPENTRY WAPIST_LVBKIMAGE(XppParamList );
XPPRET XPPENTRY WAPIST_LVCOLUMN(XppParamList );
XPPRET XPPENTRY WAPIST_LVFINDINFO(XppParamList );
XPPRET XPPENTRY WAPIST_LVFOOTERINFO(XppParamList );
XPPRET XPPENTRY WAPIST_LVFOOTERITEM(XppParamList );
XPPRET XPPENTRY WAPIST_LVGROUP(XppParamList );
XPPRET XPPENTRY WAPIST_LVGROUPMETRICS(XppParamList );
XPPRET XPPENTRY WAPIST_LVHITTESTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_LVINSERTGROUPSORTED(XppParamList );
XPPRET XPPENTRY WAPIST_LVINSERTMARK(XppParamList );
XPPRET XPPENTRY WAPIST_LVITEM(XppParamList );
XPPRET XPPENTRY WAPIST_LVITEMINDEX(XppParamList );
XPPRET XPPENTRY WAPIST_LVSETINFOTIP(XppParamList );
XPPRET XPPENTRY WAPIST_LVTILEINFO(XppParamList );
XPPRET XPPENTRY WAPIST_LVTILEVIEWINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMITEMACTIVATE(XppParamList );
XPPRET XPPENTRY WAPIST_NMLISTVIEW(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVCACHEHINT(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVCUSTOMDRAW(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVDISPINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVEMPTYMARKUP(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVFINDITEM(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVGETINFOTIP(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVKEYDOWN(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVLINK(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVODSTATECHANGE(XppParamList );
XPPRET XPPENTRY WAPIST_NMLVSCROLL(XppParamList );
XPPRET XPPENTRY WAPIST_LITEM(XppParamList );
XPPRET XPPENTRY WAPIST_NMCUSTOMDRAW(XppParamList );
// ----------------------------------------

XPPRET XPPENTRY WAPIST_WINDOWPOS(XppParamList );
XPPRET XPPENTRY WAPIST_COLORSCHEME(XppParamList );
XPPRET XPPENTRY WAPIST_DPASTREAMINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMCHAR(XppParamList );
XPPRET XPPENTRY WAPIST_NMCUSTOMSPLITRECTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMCUSTOMTEXT(XppParamList );
XPPRET XPPENTRY WAPIST_NMKEY(XppParamList );
XPPRET XPPENTRY WAPIST_NMMOUSE(XppParamList );
XPPRET XPPENTRY WAPIST_NMOBJECTNOTIFY(XppParamList );
XPPRET XPPENTRY WAPIST_NMTOOLTIPSCREATED(XppParamList );
XPPRET XPPENTRY WAPIST_READERMODEINFO(XppParamList );
XPPRET XPPENTRY WAPIST_BUTTON_IMAGELIST(XppParamList );
XPPRET XPPENTRY WAPIST_BUTTON_SPLITINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMBCDROPDOWN(XppParamList );
XPPRET XPPENTRY WAPIST_NMBCHOTITEM(XppParamList );
XPPRET XPPENTRY WAPIST_COMBOBOXINFO(XppParamList );
XPPRET XPPENTRY WAPIST_COMPAREITEMSTRUCT(XppParamList );
XPPRET XPPENTRY WAPIST_DRAWITEMSTRUCT(XppParamList );
XPPRET XPPENTRY WAPIST_MEASUREITEMSTRUCT(XppParamList );
XPPRET XPPENTRY WAPIST_COMBOBOXEXITEM(XppParamList );
XPPRET XPPENTRY WAPIST_NMCBEDRAGBEGIN(XppParamList );
XPPRET XPPENTRY WAPIST_NMCBEENDEDIT(XppParamList );
XPPRET XPPENTRY WAPIST_NMCOMBOBOXEX(XppParamList );
XPPRET XPPENTRY WAPIST_DATETIMEPICKERINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMDATETIMECHANGE(XppParamList );
XPPRET XPPENTRY WAPIST_NMDATETIMEFORMAT(XppParamList );
XPPRET XPPENTRY WAPIST_NMDATETIMEFORMATQUERY(XppParamList );
XPPRET XPPENTRY WAPIST_NMDATETIMESTRING(XppParamList );
XPPRET XPPENTRY WAPIST_NMDATETIMEWMKEYDOWN(XppParamList );
XPPRET XPPENTRY WAPIST_DRAGLISTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_EDITBALLOONTIP(XppParamList );
XPPRET XPPENTRY WAPIST_HDHITTESTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_HDITEM(XppParamList );
XPPRET XPPENTRY WAPIST_HDLAYOUT(XppParamList );
XPPRET XPPENTRY WAPIST_HDTEXTFILTER(XppParamList );
XPPRET XPPENTRY WAPIST_NMHDDISPINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMHDFILTERBTNCLICK(XppParamList );
XPPRET XPPENTRY WAPIST_NMHEADER(XppParamList );


XPPRET XPPENTRY WAPIST_NMIPADDRESS(XppParamList );
XPPRET XPPENTRY WAPIST_DELETEITEMSTRUCT(XppParamList );
XPPRET XPPENTRY WAPIST_MCGRIDINFO(XppParamList );
XPPRET XPPENTRY WAPIST_MCHITTESTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMDAYSTATE(XppParamList );
XPPRET XPPENTRY WAPIST_NMSELCHANGE(XppParamList );
XPPRET XPPENTRY WAPIST_NMVIEWCHANGE(XppParamList );
XPPRET XPPENTRY WAPIST_NMPGCALCSIZE(XppParamList );
XPPRET XPPENTRY WAPIST_NMPGHOTITEM(XppParamList );
XPPRET XPPENTRY WAPIST_NMPGSCROLL(XppParamList );
XPPRET XPPENTRY WAPIST_PBRANGE(XppParamList );



XPPRET XPPENTRY WAPIST_NMREBARSPLITTER(XppParamList );



XPPRET XPPENTRY WAPIST_SCROLLBARINFO(XppParamList );
XPPRET XPPENTRY WAPIST_SCROLLINFO(XppParamList );
XPPRET XPPENTRY WAPIST_LHITTESTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMLINK(XppParamList );
XPPRET XPPENTRY WAPIST_NMTCKEYDOWN(XppParamList );
XPPRET XPPENTRY WAPIST_TCHITTESTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_TCITEM(XppParamList );
XPPRET XPPENTRY WAPIST_TCITEMHEADER(XppParamList );
XPPRET XPPENTRY WAPIST_COLORMAP(XppParamList );
XPPRET XPPENTRY WAPIST_NMTBCUSTOMDRAW(XppParamList );
XPPRET XPPENTRY WAPIST_NMTBDISPINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMTBGETINFOTIP(XppParamList );
XPPRET XPPENTRY WAPIST_NMTBHOTITEM(XppParamList );
XPPRET XPPENTRY WAPIST_NMTBRESTORE(XppParamList );
XPPRET XPPENTRY WAPIST_NMTBSAVE(XppParamList );
XPPRET XPPENTRY WAPIST_NMTOOLBAR(XppParamList );
XPPRET XPPENTRY WAPIST_TBADDBITMAP(XppParamList );

XPPRET XPPENTRY WAPIST_TBBUTTONINFOA(XppParamList );
XPPRET XPPENTRY WAPIST_TBINSERTMARK(XppParamList );
XPPRET XPPENTRY WAPIST_TBMETRICS(XppParamList );
XPPRET XPPENTRY WAPIST_TBREPLACEBITMAP(XppParamList );
XPPRET XPPENTRY WAPIST_TBSAVEPARAMS(XppParamList );
XPPRET XPPENTRY WAPIST_NMTTCUSTOMDRAW(XppParamList );
XPPRET XPPENTRY WAPIST_NMTTDISPINFO(XppParamList );
XPPRET XPPENTRY WAPIST_TOOLINFO(XppParamList );
XPPRET XPPENTRY WAPIST_TTGETTITLE(XppParamList );
XPPRET XPPENTRY WAPIST_TTHITTESTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMTREEVIEW(XppParamList );
XPPRET XPPENTRY WAPIST_NMTVASYNCDRAW(XppParamList );
XPPRET XPPENTRY WAPIST_NMTVCUSTOMDRAW(XppParamList );
XPPRET XPPENTRY WAPIST_NMTVDISPINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMTVDISPINFOEX(XppParamList );
XPPRET XPPENTRY WAPIST_NMTVGETINFOTIP(XppParamList );
XPPRET XPPENTRY WAPIST_NMTVITEMCHANGE(XppParamList );
XPPRET XPPENTRY WAPIST_NMTVKEYDOWN(XppParamList );
XPPRET XPPENTRY WAPIST_NMTVSTATEIMAGECHANGING(XppParamList );
XPPRET XPPENTRY WAPIST_TVGETITEMPARTRECTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_TVHITTESTINFO(XppParamList );
XPPRET XPPENTRY WAPIST_TVINSERTSTRUCT(XppParamList );
XPPRET XPPENTRY WAPIST_TVITEM(XppParamList );
XPPRET XPPENTRY WAPIST_TVITEMEX(XppParamList );
XPPRET XPPENTRY WAPIST_TVSORTCB(XppParamList );
XPPRET XPPENTRY WAPIST_NMUPDOWN(XppParamList );
XPPRET XPPENTRY WAPIST_UDACCEL(XppParamList );
XPPRET XPPENTRY WAPIST_URL_COMPONENTS(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_ASYNC_RESULT(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_DIAGNOSTIC_SOCKET_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_PROXY_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_PER_CONN_OPTION(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_PER_CONN_OPTION_LIST(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_VERSION_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_HTTP_VERSION_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_CONNECTED_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_CERTIFICATE_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_BUFFERS(XppParamList );
XPPRET XPPENTRY WAPIST_INCOMINGCOOKIESTATE(XppParamList );
XPPRET XPPENTRY WAPIST_OUTGOINGCOOKIESTATE(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNETCOOKIEHISTORY(XppParamList );
XPPRET XPPENTRY WAPIST_COOKIEDECISION(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_AUTH_NOTIFY_DATA(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_CACHE_ENTRY_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_CACHE_TIMESTAMPS(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_CACHE_GROUP_INFO(XppParamList );
XPPRET XPPENTRY WAPIST_AUTO_PROXY_SCRIPT_BUFFER(XppParamList );
XPPRET XPPENTRY WAPIST_INTERNET_PER_CONN_OPTION___VALUE(XppParamList );

XPPRET XPPENTRY WAPIST_TRACKMOUSEEVENT(XppParamList );
XPPRET XPPENTRY WAPIST_MOUSEMOVEPOINT(XppParamList );
XPPRET XPPENTRY WAPIST_PREVENT_MEDIA_REMOVAL(XppParamList );
XPPRET XPPENTRY WAPIST_SHFILEINFO(XppParamList );
XPPRET XPPENTRY WAPIST_NMSELCHANGE(XppParamList );
XPPRET XPPENTRY WAPIST_SHELLEXECUTEINFO(XppParamList );




//-----------------------------------------------------------------------------
//////////  UNKNOW LINE #1176>>>-----------------------------------------<<<
// -------------------------  C EXPORTED FUNCTIONS
//////////  UNKNOW LINE #1178>>>_CDECL_EXPORT_( _conGetFloat  )<<<
//////////  UNKNOW LINE #1179>>>_CDECL_EXPORT_( _conPutFloat  )<<<
//////////  UNKNOW LINE #1180>>>_CDECL_EXPORT_( _conGetQWord  )<<<
//////////  UNKNOW LINE #1181>>>_CDECL_EXPORT_( _conPutQWord  )<<<
// ---------------------------------------------------------------------------
#ifdef __cplusplus
}
#endif
// ---------------------------------------------------------------------------
